### ISSUE TITLE
Roadmap V1

### ISSUE THREAD

**Issue by morgangiraud** [stockmouton/lenia.stockmouton.com#5]
What should be ready for the launch!

#### Engineering
- [x] Finish classification
- [x] Finish filling all Lenias metadata (lorem ipsum for description and id for name)
- [x] Prototype Orbium with categories for the Smart contract
- [x] Push those fake 210 fake Orbium into the smart contract

#### Crypto
- [x] Create a first smart contract and link it with the website
- [x] Deploy on a Testnet
- [x] Buy stockmouton.eth -> https://app.ens.domains/name/stockmouton.eth (Waiting for lower gas price)
- [x] Buy lenia.world

#### Website
- [x] Web site: publish this roadmap and open-source the website <- write "TBA" where we don't have the content yet

#### Partnership
- [x] Explore partnership options with the researcher Bert Chan [partnership]
- [x] Explore partnership with NFTribe for the communication [partnership]

#### Social
- [x] Have a Lenia logo [social]
- [x] Try to reach the original Lenia Twitter account [social]
- [x] Have a Stockmouton logo [social]
- [x] Finish our official description for discord and Twitter [social]
- [x] Configure Discord properly (a nice mix of simpleness and best practice) [social]

--- 

- [x] Deploy

#### Engineering
- [x] Reach 200 Lenia
- [x] Explore improved colors and rendering quality
- [x] Build the JS rendering engine
- [x] Script for uploading the Lenia metadata to the blockchain once it's minted
- [x] When you click, your own Lenia pop in the rendering engine

#### Smart Contract
- [x] Add Lenia metadata to smart contract
- [x] Integrate JS engine inside smart contract
- [x] Implement whitelist minting function
- [x] Payment splitting between different entities for primary sale
- [x] Write integration tests for smart contract
- [x] Make the testing marketplace on Opensea and connect it to our smart contract
- [x] Estimate overall cost of deploying smart contract and potential later external function calls
- [x] Royalties smart contract for Opensea
- [x] Test WalletConnect
- [x] Move the renderer onchain

#### Website
- [x] Have a page pre-minting and another one for production
- [x] Add UI for members who have a pre-sale mint pass
- [x] Finish LeniaDEX (2d map of creatures + dex of attributes, show own creatures to owner, show placeholder image for the ones not revealed)
- [x] Page for each Lenia: URL with Lenia ID, fetch metadata from smart contract and render Lenia
- [x] Connect to Metamask automatically if already done before
- [x] Check SEO attributes
- [x] Google analytics
- [x] Make the background video follow the user when scrolling
- [x] Add a confirmation popup on the transaction receipt
- [x] Website content (might be cool to add notebooks for math [wizard](https://colab.research.google.com/github/OpenLenia/Lenia-Tutorial/blob/main/Tutorial_From_Conway_to_Lenia.ipynb#scrollTo=Blf4zJOuRjIO) [beta]
- [x] Website meta-content
- [x] Cross website checking
- [x] Make it responsive

#### Social
- [x] Start following people on Twitter [beta]
- [x] Start bootstrapping the community [beta]

#### Partnership
- [ ] Explore possibilities to redistribute TBA% of sales to an association which help marine creatures survive in our world [beta]

## Prod
- [x] Make the production marketplace on Opensea and connect it to our smart contract
- [x] https://snapshot.org/#/stockmouton.eth

**Comment by leader-sheep** [comment]
DONE
